name: Bicep Build

on:
  push:
    paths:
      - "deploy/**"
      - ".github/workflows/bicep-build.yml"
  pull_request:
    paths:
      - "deploy/**"
      - ".github/workflows/bicep-build.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Azure CLI version
        run: az version

      - name: Build Bicep
        run: az bicep build --file deploy/main.bicep
